Algoritmo "paraaninhado"

Var
// Seção de Declarações das variáveis 
i,j: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 10 faça
escreva ("Valor de I: ", i)
para j de 1 ate 3 faça
escreva ("J: ",j)
fimpara
fimpara
//o para faz um loping enquanto esse nao alcançar esse valor ele nao para.
// vai fazer a execução ate valer 3
Fimalgoritmo